// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int64
	Title       pgtype.Text
	Description pgtype.Text
	Done        pgtype.Bool
}
